# Generated by Django 4.2.2 on 2023-06-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('colonge_name', models.CharField(max_length=200)),
                ('colonge_image', models.ImageField(max_length=1000, upload_to='static/media')),
                ('colonge_url', models.URLField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('player_image', models.ImageField(max_length=1000, upload_to='static/media')),
            ],
        ),
    ]
