# Generated by Django 4.2.2 on 2023-06-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonge',
            name='colonge_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='colonge',
            name='player_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
