# Generated by Django 4.2.2 on 2023-06-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0002_alter_colonge_colonge_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonge',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
