# Generated by Django 4.2.2 on 2023-06-21 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0003_alter_colonge_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colonge',
            new_name='Scent',
        ),
    ]
