# Generated by Django 4.1.6 on 2023-06-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0006_alter_scent_colonge_image_alter_scent_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scent',
            name='colonge_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='scent',
            name='player_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
