# Generated by Django 4.1.6 on 2023-06-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0008_alter_scent_colonge_image_alter_scent_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scent',
            name='colonge_image',
            field=models.ImageField(blank='True', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='scent',
            name='player_image',
            field=models.ImageField(blank='True', upload_to='images/'),
        ),
    ]
