# Generated by Django 4.1.6 on 2023-06-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0009_alter_scent_colonge_image_alter_scent_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scent',
            name='header',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
