# Generated by Django 4.1.6 on 2023-06-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0010_scent_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scent',
            name='description',
        ),
        migrations.AddField(
            model_name='scent',
            name='application',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='scent',
            name='why',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
