# Generated by Django 4.1.6 on 2023-06-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0011_remove_scent_description_scent_application_scent_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='scent',
            name='header_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
