# Generated by Django 4.1.6 on 2023-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0013_comparison_basketballessential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_player', models.CharField(blank=True, max_length=400)),
                ('name_watch', models.CharField(blank=True, max_length=400)),
                ('img_watch', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
        ),
    ]
