# Generated by Django 4.1.6 on 2023-07-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletejournalapp', '0015_watch_img_player_alter_watch_img_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballessential',
            name='comparison',
        ),
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
